"""
Django settings for bbgi project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-+dfyt)%ptso@3-oi2yt!1p_++61q0&ldzvg#(-3l3ocut73lsm"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    
    "core",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "bbgi.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "bbgi.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

CORS_ALLOWED_ORIGINS = [
    "https://customsstatistics.netlify.app",
]
CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = []

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Media files
MEDIA_URL = "/stmedia/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# PostgreSQL Database Configuration
DB_HOST = os.environ.get('DB_HOST', '94.130.176.68')
DB_PORT = os.environ.get('DB_PORT', '5432')
DB_NAME = os.environ.get('DB_NAME', 'statdb')
DB_USER = os.environ.get('DB_USER', 'stat')
DB_PASSWORD = os.environ.get('DB_PASSWORD', 'stat')

# QP Agent Database Configuration (for risk_fin sync)
QP_AGENT_DB_NAME = os.environ.get('QP_AGENT_DB_NAME', 'qp_agent')
QP_AGENT_DB_HOST = os.environ.get('QP_AGENT_DB_HOST', DB_HOST)
QP_AGENT_DB_PORT = os.environ.get('QP_AGENT_DB_PORT', DB_PORT)
QP_AGENT_DB_USER = os.environ.get('QP_AGENT_DB_USER', 'qp_agent')
QP_AGENT_DB_PASSWORD = os.environ.get('QP_AGENT_DB_PASSWORD', DB_PASSWORD)

# QMatic API Configuration
QMATIC_AUTH_USER = os.environ.get('QMATIC_AUTH_USER', 'superadmin')
QMATIC_AUTH_PASSWORD = os.environ.get('QMATIC_AUTH_PASSWORD', '19921992Mr%')

# Samba Server Configuration
SAMBA_SERVER_IP = os.environ.get('SAMBA_SERVER_IP', '23.88.99.92')
SAMBA_SERVER_NAME = os.environ.get('SAMBA_SERVER_NAME', 'DEBIAN-SERVER')
SAMBA_SHARE_NAME = os.environ.get('SAMBA_SHARE_NAME', 'Share')
SAMBA_USERNAME = os.environ.get('SAMBA_USERNAME', 'sambauser')
SAMBA_PASSWORD = os.environ.get('SAMBA_PASSWORD', '1')

# Audio Encryption Key
ENCRYPTION_KEY = os.environ.get('ENCRYPTION_KEY', 'YUfrhpimMr-lkxklJq48554vm7KAJN1TSI7FXMyp2Hw=')

# Development Mode - Use post_xml instead of get_customer_info
USE_POST_XML = os.environ.get('USE_POST_XML', 'False').lower() == 'true'

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'core.api.views': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}